blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.renderPosts, name="posts"),
    path("<int:post_id>", views.post_detail, name="post_detail"),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  views.home),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images")
    date = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.title

portfolio/models.py
from django.db import models

from django.db import models
from django.db.models.fields import CharField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images")
    url = URLField(blank=True)
    date = DateField(default=date.today)

    def __str__(self) -> str:
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def renderPosts(request):
    total_posts = Post.objects.count()
    posts = Post.objects.order_by("-date")
    return render(request, "blog.html", {"posts": posts, "total_posts": total_posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
from blog.models import Post  # Importa el modelo de blog

def home(request):
    projects = Project.objects.all()
    posts = Post.objects.order_by("-date")  # Consulta para obtener los posts
    total_posts = posts.count()  # Cuenta total de posts
    return render(request, 'home.html', {'projects': projects, 'posts': posts, 'total_posts': total_posts})

blog/templates/blog.html
  <div id="blogs" class="container text-center my-5">
    <h3>Blogs</h3>
    <div class="row mt-4 d-flex justify-content-center">
      {% for post in posts %}
        <div class="col-md-4 d-flex align-items-stretch mb-4"> <!-- Agregado 'mb-4' para margen inferior -->
          <div class="p-4 border rounded shadow-sm blog-box box w-100">
            <!-- Título del blog -->
            <h4 class="blog-title mt-3">{{ post.title }}</h4>

            <!-- Descripción y fecha del blog -->
            <p>{{ post.description|striptags|truncatechars:100 }}</p>
            <p class="text-muted">{{ post.date|date:'M d Y'|upper }}</p>

            <!-- Botón de enlace al detalle del blog -->
            <a href="{% url 'blog:post_detail' post.id %}" class="blog-boton" rel="noreferrer" title="Leer más sobre {{ post.title }}">
              <svg version="1.1" id="_x32_" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve" fill="00000" width="24" height="24">
                <g>
                  <path d="M421.073,221.719c-0.578,11.719-9.469,26.188-23.797,40.094v183.25c-0.016,4.719-1.875,8.719-5.016,11.844 
                  c-3.156,3.063-7.25,4.875-12.063,4.906H81.558c-4.781-0.031-8.891-1.844-12.047-4.906c-3.141-3.125-4.984-7.125-5-11.844V152.219 
                  c0.016-4.703,1.859-8.719,5-11.844c3.156-3.063,7.266-4.875,12.047-4.906h158.609c12.828-16.844,27.781-34.094,44.719-49.906 
                  c0.078-0.094,0.141-0.188,0.219-0.281H81.558c-18.75-0.016-35.984,7.531-48.25,19.594c-12.328,12.063-20.016,28.938-20,47.344 
                  v292.844c-0.016,18.406,7.672,35.313,20,47.344C45.573,504.469,62.808,512,81.558,512h298.641c18.781,0,36.016-7.531,48.281-19.594 
                  c12.297-12.031,20-28.938,19.984-47.344V203.469c0,0-0.125-0.156-0.328-0.313C440.37,209.813,431.323,216.156,421.073,221.719z"/>
                  <path d="M498.058,0c0,0-15.688,23.438-118.156,58.109C275.417,93.469,211.104,237.313,211.104,237.313 
                  c-15.484,29.469-76.688,151.906-76.688,151.906c-16.859,31.625,14.031,50.313,32.156,17.656 
                  c34.734-62.688,57.156-119.969,109.969-121.594c77.047-2.375,129.734-69.656,113.156-66.531c-21.813,9.5-69.906,0.719-41.578-3.656 
                  c68-5.453,109.906-56.563,96.25-60.031c-24.109,9.281-46.594,0.469-51-2.188C513.386,138.281,498.058,0,498.058,0z"/>
                </g>
              </svg>
            </a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="container d-flex flex-column align-items-center justify-content-center my-5">
  <div class="text-center" style="max-width: 800px;">
    <!-- Título del blog -->
    <h1>{{ post.title }}</h1>
    <h2 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h2>

    <!-- Imagen del blog -->
    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid rounded mb-4">

    <!-- Descripción del blog -->
    <div class="my-4">
      {{ post.description|safe }}
    </div>
  </div>
</div>

{% endblock %}

portfolio/templates/contacto.html
{% load static %}


<body>
    <div id="contacto" class="section container my-5">
        <div class="d-flex flex-column align-items-center">
            <!-- Título -->
            <h3 id="contactoh3" class="text-center mb-4">Contáctame</h3>
            
            <!-- SVG y Correo en línea -->
            <div class="d-flex align-items-center mb-3 contact-info">
                <svg viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="24" height="24">
                    <path d="M2.54433 5.16792C3.0468 4.46923 3.86451 4 4.8 4H19.2C20.1355 4 20.9532 4.46923 21.4557 5.16792C21.7993 5.64567 22 6.235 22 6.86667V17.1333C22 18.682 20.7804 20 19.2 20H4.8C3.21964 20 2 18.682 2 17.1333V6.86667C2 6.23499 2.20074 5.64567 2.54433 5.16792ZM4.9327 6L11.2598 12.9647C11.6566 13.4015 12.3434 13.4015 12.7402 12.9647L19.0673 6H4.9327ZM20 7.94766L14.2205 14.3096C13.0301 15.6199 10.9699 15.6199 9.77948 14.3096L4 7.94766V17.1333C4 17.6466 4.39214 18 4.8 18H19.2C19.6079 18 20 17.6466 20 17.1333V7.94766Z"></path>
                </svg>
                <a href="mailto:nicolasbarriosgarcia1@gmail.com" title="Enviar correo" class="ml-2">
                    nicolasbarriosgarcia1@gmail.com
                </a>
            </div>

            <!-- Botón para descargar el CV -->
            <a id="cv" class="btn btn-primary btn-lg rounded-0 my-3 shadow-effect" href="{% static 'portfolio/cv.pdf' %}" download>
                Descarga mi CV
            </a>
        </div>
    </div>
</body>

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Porfolio</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="text-light">

  {% include 'partials/navbar.html' %}

  <div class="container p-4">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

<link rel="stylesheet" href="{% static 'main.css' %}">
<script src="{% static 'scripts.js' %}"></script>